version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: starknet_vault_kit
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  indexer:
    build:
      context: .
      dockerfile: Dockerfile.indexer
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/starknet_vault_kit
      - RPC_URL=${RPC_URL:-https://starknet-mainnet.public.blastapi.io}
      - APIBARA_TOKEN=${APIBARA_TOKEN}
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/starknet_vault_kit
      - RPC_URL=${RPC_URL:-https://starknet-mainnet.public.blastapi.io}
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data: