# version: '3.8'  # obsolete attribute

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: starknet_vault_kit
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  indexer:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: indexer
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/starknet_vault_kit
      - RPC_URL=${RPC_URL:-https://starknet-mainnet.public.blastapi.io}
      - APIBARA_TOKEN=${APIBARA_TOKEN}
      - VAULT_ADDRESS=${VAULT_ADDRESS}
      - START_BLOCK=${START_BLOCK}
      - FORCE_START_BLOCK=${FORCE_START_BLOCK}
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    command: >
      sh -c "
        echo '✅ Starting migration and indexer...';
        npx prisma migrate deploy;
        echo '✅ Migration done! Starting Indexer...';
        pnpm run dev:indexer
      "

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: api
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/starknet_vault_kit
      - RPC_URL=${RPC_URL:-https://starknet-mainnet.public.blastapi.io}
      - VAULT_ADDRESS=${VAULT_ADDRESS}
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    command: >
      sh -c "
        echo '✅ Starting migration and API...';
        npx prisma migrate deploy;
        echo '✅ Migration done! Starting API...';
        pnpm run dev:api
      "

volumes:
  postgres_data: